### ISSUE TITLE
Just picking nits

### ISSUE THREAD

**Issue by Discordanian** [byuksel/Automake-Autoconf-Template-Project#1]
If you add the .h files to the _SOURCES directives in Makefile.am then when you do a 'make dist' it'll include those header file.  Also, if you make a change to the .h file you'll get a new binary which is the correct behavior.    (Love this project and I'm recommending this project for folks doing C++ in a *nix environment).

**Comment by byuksel** [comment]
Thank you for the feedback @Discordanian. This is great. I'll make the changes now. If you have other suggestions, please do not hesitate to send a pull request.

**Comment by byuksel** [comment]
Fixed with https://github.com/byuksel/Automake-Autoconf-Template-Project/commit/c68ffd05045e31002e47b57897850329835e4b3e
